"""empty message

Revision ID: 6f6a5cfcad6d
Revises: 7271f4cd1721
Create Date: 2019-09-02 20:58:18.549619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f6a5cfcad6d'
down_revision = '7271f4cd1721'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_contacts_username'), 'contacts', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contacts_username'), table_name='contacts')
    # ### end Alembic commands ###
