"""empty message

Revision ID: c49aedae1fdd
Revises: 6f6a5cfcad6d
Create Date: 2019-09-02 22:29:34.693342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c49aedae1fdd'
down_revision = '6f6a5cfcad6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'created_at')
    # ### end Alembic commands ###
